services:
  frontend:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.entrypoints=web, websecure"
      - "traefik.http.routers.frontend.rule=Host(`studioway11.com`)"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=tls-production"

    expose:
      - 80
    networks:
      - traefik

networks:
  traefik:
    name: traefik
    external: true